### ISSUE TITLE
Controlling deps version

### ISSUE THREAD

**Issue by julien-f** [developit/babel-preset-stage-0-kneden#2]
This package currently uses wildcards as versions for both `babel-preset-stage-0` and `babel-plugin-async-to-promise` which prevent users from deciding which versions they use and it will probably break on major versions.

As far as I see there are two possibilities:
- use more precise versions and keep updating your package ([Greenkeeper](https://greenkeeper.io/) might help)
- use peer dependencies and let users install the deps themselves.

**Comment by developit** [comment]
Ah - I had meant to change those to peer deps.  Will do.

**Comment by developit** [comment]
Fixed in 6a60eb0 :)
